excluded:
 - Pods
 - ZURAZU/ZURAZUTests
disabled_rules:
 - control_statement
 - trailing_whitespace
 - vertical_whitespace
 - trailing_newline
 - switch_case_alignment
 - identifier_name
line_length: 180
