# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZURAZU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CombineCocoa'
	pod 'CombineDataSources'
	pod 'SwiftLint'
  # Pods for ZURAZU
  
  target 'ZURAZUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZURAZUUITests' do
    # Pods for testing
  end

end
